kind: ConfigMap
apiVersion: v1
metadata:
  name: app-as3-1-partition-2-vs
  namespace: f5-test002
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true,
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.11.0",
        "id": "one_partition_two_vs",
        "label": "f5_test002",
        "remark": "HTTP application",
        "f5_test002": {
          "class": "Tenant",
          "f5_test002_1": {
            "class": "Application",
            "template": "generic",
            "app_1_svc_vs": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                "10.1.10.61"
              ],
              "virtualPort": 80,
              "pool": "app_1_svc_pool"
            },
            "app_1_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          },
           "f5_test002_2": {
            "class": "Application",
            "template": "generic",
            "app_2_svc_vs": {
              "class": "Service_HTTP",
              "virtualAddresses": [
                "10.1.10.62"
              ],
              "virtualPort": 80,
              "pool": "app_2_svc_pool"
            },
            "app_2_svc_pool": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": [
              {
                "servicePort": 80,
                "serverAddresses": []
              }
              ]
            }
          }
        }
      }
    }