kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-a2-declaration
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.18.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "https",
            "remark": "A2 Template",
            "A2": {
                "class": "Tenant",
            }
        }
    }
